name: Validate OpenAPI specs



on:
  pull_request:
    branches:
      - master
      - develop
      - 'release/*'

jobs:
  openapi-spec:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/portainer/*
    steps:
    - uses: actions/checkout@v3
    - uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY_LIBLICENSE }}

    - uses: actions/setup-go@v3
      with:
        go-version: '1.18'

    - name: Configure git for private modules
      run: git config --global url."git@github.com:".insteadOf "https://github.com"

    - name: Download golang modules
      run: cd ./api && go get -t -v -d ./...
    - uses: actions/setup-node@v3
      with:
          node-version: '14'
          cache: 'yarn'
    - run: yarn --frozen-lockfile
    
    - name: Build OpenAPI 2.0 Spec
      run: yarn build:docs

    
    # OpenAPI2.0 does not support multiple body params (which we utilize in some of our handlers).
    # OAS3.0 however does support multiple body params - hence its best to convert the generated OAS 2.0
    # to OAS 3.0 and validate the output of generated OAS 3.0 instead.
    - name: Convert OpenAPI 2.0 to OpenAPI 3.0 and validate spec
      run: yarn validate:docs
